"""
atlas_snap.py
=============
Post-processing script that improves atlas labelling for coordinates that
fall in atlas gaps (no_region) by snapping them to the nearest cortical
surface point and re-looking up the atlas label there.

Works on:
  - The group-level shared CSV (all_subjects_mni.csv) — requires that it
    was generated by the updated stage_05 which includes fs_x/fs_y/fs_z
    and snap_distance_mm columns
  - Per-subject targets_summary.csv files

Algorithm
---------
For each coordinate where region_X == "no_region":
  1. Check snap_distance_mm (fsaverage surface snap, already computed)
  2. If snap_distance_mm <= max_snap_mm (default 5mm):
     a. Look up atlas label at snapped surface coordinate [fs_x, fs_y, fs_z]
     b. If valid label found: use it, record snap distance
     c. If still no_region: keep no_region
  3. If snap_distance_mm > max_snap_mm: keep no_region

This approach is anatomically correct — the fsaverage snap moves
perpendicular to the cortical surface, not diagonally through white
matter. The 5mm limit prevents snapping to anatomically implausible
regions.

Atlases snapped
---------------
Harvard-Oxford, Destrieux, Schaefer 100-1000.
(AAL and Yeo excluded — AAL has download issues; Yeo is network-level
and snapping to the nearest network boundary is not meaningful.)

Output columns added
--------------------
  region_{atlas}_snapped   — label after snapping (same as original if
                             original was already valid)
  region_{atlas}_snap_mm   — snap distance in mm (NaN if not snapped)

Usage
-----
  # Group CSV (most common use case)
  python atlas_snap.py \\
      --input  group_viz/all_subjects_mni.csv \\
      --output group_viz/all_subjects_mni_snapped.csv

  # Per-subject summary CSV
  python atlas_snap.py \\
      --input  derivatives/sub-ou1c001/coordinates/targets_summary.csv \\
      --output derivatives/sub-ou1c001/coordinates/targets_summary_snapped.csv

  # All subjects in derivatives directory
  python atlas_snap.py \\
      --derivatives-dir /path/to/derivatives \\
      --output-suffix _snapped

  # Custom snap distance
  python atlas_snap.py \\
      --input all_subjects_mni.csv \\
      --output all_subjects_mni_snapped.csv \\
      --max-snap-mm 10
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

SNAP_ATLASES = [
    "harvard_oxford",
    "destrieux",
    "schaefer_100",
    "schaefer_200",
    "schaefer_300",
    "schaefer_400",
    "schaefer_500",
    "schaefer_600",
    "schaefer_700",
    "schaefer_800",
    "schaefer_900",
    "schaefer_1000",
]

NO_REGION_VALUES = {"no_region", "out_of_bounds", "atlas_unavailable", "atlas_error"}
DEFAULT_MAX_SNAP_MM = 5.0

_atlas_cache: dict = {}


# =============================================================================
# Atlas loading
# =============================================================================

def _load_atlas(key: str):
    if key in _atlas_cache:
        return _atlas_cache[key]

    try:
        import nibabel as nib
        from nilearn import datasets

        if key == "harvard_oxford":
            ho     = datasets.fetch_atlas_harvard_oxford(
                         "cort-maxprob-thr25-1mm", symmetric_split=True)
            img    = ho.maps
            labels = [l.decode("utf-8") if isinstance(l, bytes) else l
                      for l in ho.labels]

        elif key == "destrieux":
            dest   = datasets.fetch_atlas_destrieux_2009(lateralized=True)
            img    = nib.load(dest.maps)
            labels = [l.decode("utf-8") if isinstance(l, bytes) else l
                      for l in dest.labels]

        elif key.startswith("schaefer_"):
            n      = int(key.split("_")[1])
            sch    = datasets.fetch_atlas_schaefer_2018(n_rois=n)
            img    = nib.load(sch.maps)
            labels = ["background"] + [
                l.decode("utf-8") if isinstance(l, bytes) else l
                for l in sch.labels
            ]

        else:
            return None, None, None

        if isinstance(img, (str, Path)):
            img = nib.load(str(img))

        data   = img.get_fdata().astype(int)
        affine = img.affine
        _atlas_cache[key] = (data, affine, labels)
        print(f"  Loaded: {key} ({len(labels)} labels)")
        return data, affine, labels

    except Exception as e:
        print(f"  WARNING: Could not load {key}: {e}")
        return None, None, None


def _lookup_point(mm: np.ndarray, data, affine, labels) -> str:
    inv = np.linalg.inv(affine)
    vox = np.round((inv @ np.append(mm, 1))[:3]).astype(int)
    if not all(0 <= vox[d] < data.shape[d] for d in range(3)):
        return "out_of_bounds"
    pid = int(data[vox[0], vox[1], vox[2]])
    if pid == 0 or pid >= len(labels):
        return "no_region"
    lbl = labels[pid]
    return lbl.decode("utf-8") if isinstance(lbl, bytes) else str(lbl)


# =============================================================================
# Core snapping
# =============================================================================

def snap_atlas_labels(
    df: pd.DataFrame,
    max_snap_mm: float = DEFAULT_MAX_SNAP_MM,
) -> pd.DataFrame:
    """
    Snap no_region labels to nearest cortical surface point for all
    atlases in SNAP_ATLASES. Returns enriched DataFrame.
    """
    out = df.copy()

    has_snap = "snap_distance_mm" in df.columns
    has_fs   = all(c in df.columns for c in ["fs_x", "fs_y", "fs_z"])

    if not has_snap or not has_fs:
        print()
        print("ERROR: fs_x/fs_y/fs_z or snap_distance_mm columns not found.")
        print("  The shared CSV must be generated by the updated stage_05")
        print("  (which includes these columns). Delete your shared CSV,")
        print("  delete visualization outputs, and re-run the pipeline.")
        return out

    # Determine which atlases are present and load them
    print("\nLoading atlases...")
    atlas_data = {}
    for key in SNAP_ATLASES:
        if f"region_{key}" not in df.columns:
            continue
        data, affine, labels = _load_atlas(key)
        if data is not None:
            atlas_data[key] = (data, affine, labels)

    if not atlas_data:
        print("No atlas columns found in input CSV.")
        return out

    total_snapped = 0

    for key, (data, affine, labels) in atlas_data.items():
        col         = f"region_{key}"
        snapped_col = f"region_{key}_snapped"
        dist_col    = f"region_{key}_snap_mm"

        out[snapped_col] = out[col].copy()
        out[dist_col]    = np.nan

        needs_snap = (
            out[col].isin(NO_REGION_VALUES) &
            out["snap_distance_mm"].notna() &
            (out["snap_distance_mm"] <= max_snap_mm) &
            out["fs_x"].notna() &
            out["fs_y"].notna() &
            out["fs_z"].notna()
        )

        n_candidates = needs_snap.sum()
        n_snapped    = 0
        n_still_none = 0

        for idx in out.index[needs_snap]:
            fs_coord  = np.array([out.at[idx,"fs_x"],
                                   out.at[idx,"fs_y"],
                                   out.at[idx,"fs_z"]])
            snap_dist = out.at[idx, "snap_distance_mm"]
            new_label = _lookup_point(fs_coord, data, affine, labels)

            if new_label not in NO_REGION_VALUES:
                out.at[idx, snapped_col] = new_label
                out.at[idx, dist_col]    = round(snap_dist, 3)
                n_snapped += 1
            else:
                n_still_none += 1

        total_snapped += n_snapped
        print(f"  {col:40s}  {n_candidates:3d} candidates  "
              f"→ {n_snapped:3d} snapped  "
              f"({n_still_none} still no_region)")

    print(f"\n  Total labels recovered: {total_snapped}")
    return out


# =============================================================================
# File I/O
# =============================================================================

def process_file(
    input_path: Path,
    output_path: Path,
    max_snap_mm: float,
) -> None:
    print(f"\nInput : {input_path}")
    df  = pd.read_csv(input_path, na_values=["-", " -", "- "])
    print(f"  {len(df)} rows, {len(df.columns)} columns")

    out = snap_atlas_labels(df, max_snap_mm=max_snap_mm)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(output_path, index=False)
    print(f"\nOutput: {output_path}")
    print(f"  {len(out)} rows, {len(out.columns)} columns")


def process_derivatives(
    derivatives_dir: Path,
    output_suffix: str,
    max_snap_mm: float,
) -> None:
    csvs = sorted(derivatives_dir.glob("*/coordinates/targets_summary.csv"))
    if not csvs:
        print(f"No targets_summary.csv files found under {derivatives_dir}")
        sys.exit(1)

    print(f"Found {len(csvs)} summary CSVs")
    for csv_path in csvs:
        out_path = csv_path.parent / (csv_path.stem + output_suffix + csv_path.suffix)
        try:
            process_file(csv_path, out_path, max_snap_mm)
        except Exception as e:
            print(f"  ERROR: {csv_path}: {e}")


# =============================================================================
# CLI
# =============================================================================

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Snap no_region atlas labels to nearest cortical surface.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples
--------
  # Group CSV (after re-running visualize step to get fs_x/y/z columns)
  python atlas_snap.py \\
      --input  group_viz/all_subjects_mni.csv \\
      --output group_viz/all_subjects_mni_snapped.csv

  # All subjects in derivatives
  python atlas_snap.py \\
      --derivatives-dir /path/to/derivatives \\
      --output-suffix _snapped
""",
    )

    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument("--input", type=Path,
                      help="Single input CSV")
    mode.add_argument("--derivatives-dir", type=Path,
                      help="Process all targets_summary.csv files found within")

    p.add_argument("--output", type=Path, default=None,
                   help="Output path (with --input; default: input_snapped.csv)")
    p.add_argument("--output-suffix", default="_snapped",
                   help="Suffix for output files with --derivatives-dir")
    p.add_argument("--max-snap-mm", type=float, default=DEFAULT_MAX_SNAP_MM,
                   help=f"Max snap distance in mm (default: {DEFAULT_MAX_SNAP_MM})")

    return p.parse_args()


def main() -> None:
    args = _parse_args()

    if args.input:
        if args.output is None:
            args.output = args.input.parent / (
                args.input.stem + "_snapped" + args.input.suffix)
        process_file(args.input, args.output, args.max_snap_mm)
    else:
        process_derivatives(args.derivatives_dir, args.output_suffix,
                            args.max_snap_mm)
    print("\nDone.")


if __name__ == "__main__":
    main()